name: ConstructionSites
version: 0.9
main: com.ColonelHedgehog.Sites.Core.ConstructionSites
description: Used to create sites & creations from WorldEdit schematics.
depend: [WorldEdit, WorldGuard, Vault]
softdepend: [GriefPrevention]
commands:
  construct:
    description: Base command for building.
    aliases: [con, cs, constructionsites]